//! {{plugin_name}} - Uveddi Analysis Plugin
//!
//! {{description}}
//!
//! This plugin uses the WebAssembly Component Model with WIT bindings
//! for type-safe communication with the Uveddi host.

// Generate bindings from the WIT interface
// The path is relative to the plugin's location
wit_bindgen::generate!({
    world: "core-analysis",
    path: "wit/core-analysis.wit",
});

use std::cell::RefCell;

/// Main plugin struct that holds plugin state
struct {{plugin_struct}} {
    state: RefCell<Option<PluginState>>,
}

/// Internal plugin state stored across function calls
struct PluginState {
    config: PluginConfig,
    analysis_count: u32,
}

impl Default for {{plugin_struct}} {
    fn default() -> Self {
        Self {
            state: RefCell::new(None),
        }
    }
}

// Export the plugin to the WASM runtime
export!({{plugin_struct}});

// Implement the Guest trait generated by wit_bindgen
impl Guest for {{plugin_struct}} {
    /// Initialize the plugin with configuration and resource limits
    fn initialize(config: PluginConfig, _limits: ResourceLimits) -> Result<(), String> {
        log(LogLevel::Info, "Initializing {{plugin_name}} plugin");

        let state = PluginState {
            config,
            analysis_count: 0,
        };

        *PLUGIN_STATE.borrow_mut() = Some(state);

        log(LogLevel::Info, "{{plugin_name}} plugin initialized successfully");
        Ok(())
    }

    /// Analyze a source file and return issues and metrics
    fn analyze(file: SourceFile) -> Result<AnalysisResult, String> {
        log(LogLevel::Info, &format!("Analyzing {}", file.path));

        // Update analysis count
        if let Some(ref mut state) = *PLUGIN_STATE.borrow_mut() {
            state.analysis_count += 1;
        }

        let mut issues = Vec::new();

        // =====================================================
        // TODO: Implement your analysis logic here
        // =====================================================

        // Example: Detect TODO comments
        for (line_num, line) in file.content.lines().enumerate() {
            if let Some(col) = line.to_lowercase().find("todo") {
                issues.push(Issue {
                    id: format!("TODO-{}-{}", line_num + 1, col),
                    severity: SeverityLevel::Info,
                    category: IssueCategory::Documentation,
                    message: "TODO comment found".to_string(),
                    description: Some("Consider creating an issue tracker entry for this TODO".to_string()),
                    file: file.path.clone(),
                    span: Span {
                        start: Position {
                            line: line_num as u32 + 1,
                            column: col as u32,
                            byte_offset: 0,
                        },
                        end: Position {
                            line: line_num as u32 + 1,
                            column: (col + 4) as u32,
                            byte_offset: 0,
                        },
                    },
                    rule_id: Some("todo-comment".to_string()),
                    suggestion: Some("Create an issue tracker entry".to_string()),
                    fix: None,
                    metadata: vec![],
                });
            }
        }

        // Calculate basic metrics
        let metrics = Metrics {
            lines_of_code: file.content.lines().count() as u32,
            lines_of_comments: count_comment_lines(&file.content),
            complexity: 1,
            maintainability_index: 100.0,
            technical_debt_minutes: issues.len() as u32 * 5,
            custom_metrics: vec![
                ("issues_found".to_string(), issues.len() as f64),
            ],
        };

        log(LogLevel::Info, &format!(
            "Found {} issues in {}",
            issues.len(),
            file.path
        ));

        Ok(AnalysisResult {
            issues,
            metrics,
            dependencies: vec![],
            exports: vec![],
            duration_ms: 0,
            plugin_version: "{{version}}".to_string(),
        })
    }

    /// Return plugin metadata and capabilities
    fn get_info() -> PluginInfo {
        PluginInfo {
            id: "{{plugin_name}}".to_string(),
            name: "{{plugin_name}}".to_string(),
            version: "{{version}}".to_string(),
            description: "{{description}}".to_string(),
            author: "{{author}}".to_string(),
            license: "{{license}}".to_string(),
            homepage: None,
            supported_languages: vec![
                "rust".to_string(),
                "python".to_string(),
                "javascript".to_string(),
                "typescript".to_string(),
            ],
            detector_types: vec![
                IssueCategory::Quality,
                IssueCategory::Documentation,
            ],
            api_version: "1.0".to_string(),
            required_permissions: vec![],
        }
    }

    /// Clean up resources before plugin unload
    fn cleanup() -> Result<(), String> {
        log(LogLevel::Info, "Cleaning up {{plugin_name}} plugin");

        if let Some(ref state) = *PLUGIN_STATE.borrow() {
            log(LogLevel::Info, &format!(
                "Analyzed {} files during session",
                state.analysis_count
            ));
        }

        *PLUGIN_STATE.borrow_mut() = None;

        log(LogLevel::Info, "{{plugin_name}} plugin cleaned up successfully");
        Ok(())
    }
}

// Thread-local storage for plugin state
thread_local! {
    static PLUGIN_STATE: RefCell<Option<PluginState>> = RefCell::new(None);
}

// =====================================================
// Helper Functions
// =====================================================

/// Count lines that appear to be comments
fn count_comment_lines(content: &str) -> u32 {
    content
        .lines()
        .filter(|line| {
            let trimmed = line.trim();
            trimmed.starts_with("//")
                || trimmed.starts_with("#")
                || trimmed.starts_with("/*")
                || trimmed.starts_with("*")
                || trimmed.starts_with("'''")
                || trimmed.starts_with("\"\"\"")
        })
        .count() as u32
}

/// Check if a configuration value should be applied based on config
fn should_apply_config(key: &str) -> bool {
    if let Some(ref state) = *PLUGIN_STATE.borrow() {
        for (k, v) in &state.config.custom_settings {
            if k == key {
                return v == "true" || v == "1" || v == "yes";
            }
        }
    }
    false
}

/// Get a configuration value with a default fallback
fn get_config_value(key: &str, default: &str) -> String {
    if let Some(ref state) = *PLUGIN_STATE.borrow() {
        for (k, v) in &state.config.custom_settings {
            if k == key {
                return v.clone();
            }
        }
    }
    default.to_string()
}

// =====================================================
// Unit Tests
// =====================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_count_comment_lines() {
        let code = "// Comment\nfn main() {}\n// Another comment\n";
        assert_eq!(count_comment_lines(code), 2);
    }

    #[test]
    fn test_count_comment_lines_python() {
        let code = "# Comment\ndef main():\n    # Inline\n    pass\n";
        assert_eq!(count_comment_lines(code), 2);
    }

    #[test]
    fn test_count_comment_lines_empty() {
        let code = "fn main() {}\n";
        assert_eq!(count_comment_lines(code), 0);
    }
}
