apiVersion: v1
kind: Service
metadata:
  name: {{ include "uveddi.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "uveddi.labels" . | nindent 4 }}
    {{- include "uveddi.environmentLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  - name: metrics
    port: {{ .Values.app.ports.metrics }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "uveddi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
{{- if .Values.headlessService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uveddi.fullname" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "uveddi.labels" . | nindent 4 }}
    {{- include "uveddi.environmentLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  - name: metrics
    port: {{ .Values.app.ports.metrics }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "uveddi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  publishNotReadyAddresses: true
{{- end }}