use wasm_bindgen::prelude::*;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use wasm_bindgen_futures::JsFuture;

// Re-export commonly used types
pub use wasm_bindgen::JsValue;
pub use js_sys::{Array, Object, Reflect, JSON};

// Import AI analysis module
mod ai_analysis;
pub use ai_analysis::*;

/// Main plugin struct
#[wasm_bindgen]
pub struct UveddiAiLinter {
    config: PluginConfig,
    ai_analyzer: AiAnalyzer,
    state: HashMap<String, String>,
}

/// Plugin configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PluginConfig {
    pub severity_threshold: f32,
    pub max_issues_per_file: u32,
    pub custom_settings: HashMap<String, String>,
}

impl Default for PluginConfig {
    fn default() -> Self {
        Self {
            severity_threshold: 0.5,
            max_issues_per_file: 100,
            custom_settings: HashMap::new(),
        }
    }
}

/// Analysis result returned by the plugin
#[derive(Debug, Serialize, Deserialize)]
pub struct AnalysisResult {
    pub issues: Vec<Issue>,
    pub metrics: Metrics,
}

/// Represents an issue found by the plugin
#[derive(Debug, Serialize, Deserialize)]
pub struct Issue {
    pub id: String,
    pub severity: String,
    pub message: String,
    pub file: String,
    pub line: usize,
    pub column: usize,
    pub category: String,
    pub suggestion: Option<String>,
}

/// Code metrics calculated by the plugin
#[derive(Debug, Default, Serialize, Deserialize)]
pub struct Metrics {
    pub lines_of_code: usize,
    pub complexity: usize,
    pub maintainability_index: f64,
    pub custom_metrics: HashMap<String, f64>,
}

#[wasm_bindgen]
impl UveddiAiLinter {
    /// Create a new plugin instance
    #[wasm_bindgen(constructor)]
    pub fn new() -> Self {
        // Initialize logging for the plugin
        console_error_panic_hook::set_once();

        Self {
            config: PluginConfig::default(),
            ai_analyzer: AiAnalyzer::new(),
            state: HashMap::new(),
        }
    }

    /// Initialize the plugin with configuration
    #[wasm_bindgen]
    pub fn initialize(&mut self, config_json: &str) -> Result<(), JsValue> {
        self.config = serde_json::from_str(config_json)
            .map_err(|e| JsValue::from_str(&format!("Config parse error: {}", e)))?;
        
        log(&format!("uveddi-ai-linter plugin initialized"));
        Ok(())
    }

    /// Main analysis function
    #[wasm_bindgen]
    pub fn analyze(&self, code: &str, language: &str, file_path: &str) -> Result<JsValue, JsValue> {
        let mut issues = Vec::new();
        let mut metrics = Metrics::default();

        // Basic metrics calculation
        metrics.lines_of_code = code.lines().count();

        // Detect AI-generated patterns
        let ai_patterns_result = self.ai_analyzer.detect_ai_patterns(code, language)?;
        let ai_patterns: Vec<CodePattern> = ai_patterns_result.into_serde()
            .map_err(|e| JsValue::from_str(&format!("Failed to deserialize AI patterns: {}", e)))?;

        // Convert AI patterns to issues
        for pattern in ai_patterns {
            if pattern.ai_generated_likely {
                for (i, instance) in pattern.instances.iter().enumerate() {
                    issues.push(Issue {
                        id: format!("AI-{}-{}", pattern.name.replace(" ", "-").to_lowercase(), i),
                        severity: if pattern.confidence > 0.7 { "medium".to_string() } else { "info".to_string() },
                        message: format!("Detected AI pattern: {}", pattern.description),
                        file: file_path.to_string(),
                        line: instance.start_line as usize,
                        column: instance.start_column as usize,
                        category: "ai-detection".to_string(),
                        suggestion: Some("Review AI-generated code for correctness and optimization opportunities".to_string()),
                    });
                }
            }
        }

        // Add basic code quality checks
        if code.contains("TODO") || code.contains("FIXME") {
            issues.push(Issue {
                id: "TODO-001".to_string(),
                severity: "info".to_string(),
                message: "TODO/FIXME comment found - potentially AI-generated placeholder".to_string(),
                file: file_path.to_string(),
                line: self.find_line_number(code, "TODO").max(self.find_line_number(code, "FIXME")),
                column: 0,
                category: "maintenance".to_string(),
                suggestion: Some("Complete implementation or create proper issue tracker ticket".to_string()),
            });
        }

        // Detect potential hallucinations in comments
        let hallucination_indicators = [
            "generated by",
            "this code does",
            "automatically created",
            "placeholder implementation",
        ];

        for (line_num, line) in code.lines().enumerate() {
            let line_lower = line.to_lowercase();
            for indicator in &hallucination_indicators {
                if line_lower.contains(indicator) {
                    issues.push(Issue {
                        id: format!("HALLUCINATION-{}", line_num),
                        severity: "warning".to_string(),
                        message: format!("Potential AI hallucination in comment: '{}'", indicator),
                        file: file_path.to_string(),
                        line: line_num + 1,
                        column: 0,
                        category: "ai-verification".to_string(),
                        suggestion: Some("Verify the accuracy of this comment against actual implementation".to_string()),
                    });
                    break;
                }
            }
        }

        // Calculate complexity for AI quality assessment
        metrics.complexity = self.calculate_complexity(code);
        
        // Set custom AI metrics
        let ai_likelihood = ai_patterns.iter()
            .filter(|p| p.ai_generated_likely)
            .map(|p| p.confidence)
            .fold(0.0, |acc, c| acc + c) / ai_patterns.len().max(1) as f64;
        
        metrics.custom_metrics.insert("ai_likelihood".to_string(), ai_likelihood);
        metrics.custom_metrics.insert("pattern_count".to_string(), ai_patterns.len() as f64);

        let result = AnalysisResult { issues, metrics };
        
        // Convert to JsValue for return
        JsValue::from_serde(&result)
            .map_err(|e| JsValue::from_str(&format!("Serialization error: {}", e)))
    }

    /// Get plugin metadata
    #[wasm_bindgen]
    pub fn get_info(&self) -> JsValue {
        let info = serde_json::json!({
            "name": "uveddi-ai-linter",
            "version": "1.0.0",
            "description": "AI-powered code quality analysis with hallucination detection and verification",
            "author": "Uveddi Team"
        });

        JsValue::from_serde(&info).unwrap_or(JsValue::NULL)
    }

    /// Configure AI model
    #[wasm_bindgen]
    pub fn configure_ai_model(&mut self, config_json: &str) -> Result<(), JsValue> {
        self.ai_analyzer.configure_model(config_json)
    }

    /// Analyze code with AI (async)
    #[wasm_bindgen]
    pub async fn analyze_with_ai(&mut self, code: &str, language: &str, file_path: &str, analysis_type: &str) -> Result<JsValue, JsValue> {
        self.ai_analyzer.analyze_code(code, language, file_path, analysis_type).await
    }

    /// Detect AI-generated patterns
    #[wasm_bindgen]
    pub fn detect_ai_patterns(&self, code: &str, language: &str) -> Result<JsValue, JsValue> {
        self.ai_analyzer.detect_ai_patterns(code, language)
    }

    /// Verify claims against code
    #[wasm_bindgen]
    pub fn verify_claims(&self, claims_json: &str, context_json: &str) -> Result<JsValue, JsValue> {
        self.ai_analyzer.verify_claims(claims_json, context_json)
    }

    /// Get AI analyzer statistics
    #[wasm_bindgen]
    pub fn get_ai_statistics(&self) -> JsValue {
        self.ai_analyzer.get_statistics()
    }

    /// Cleanup resources
    #[wasm_bindgen]
    pub fn cleanup(&mut self) -> Result<(), JsValue> {
        self.state.clear();
        log(&format!("uveddi-ai-linter plugin cleaned up"));
        Ok(())
    }
}

impl UveddiAiLinter {
    /// Find line number of a pattern in code
    fn find_line_number(&self, code: &str, pattern: &str) -> usize {
        code.lines()
            .position(|line| line.contains(pattern))
            .map(|pos| pos + 1)
            .unwrap_or(0)
    }

    /// Calculate basic complexity metrics
    fn calculate_complexity(&self, code: &str) -> usize {
        // Simple cyclomatic complexity approximation
        let keywords = ["if", "else", "while", "for", "match", "case", "catch"];
        let mut complexity = 1; // Base complexity

        for keyword in &keywords {
            complexity += code.matches(keyword).count();
        }

        complexity
    }
}

// Host function bindings
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
    
    #[wasm_bindgen(js_namespace = console)]
    fn warn(s: &str);

    #[wasm_bindgen(js_namespace = console)]
    fn error(s: &str);
}

// Plugin panic hook for better error reporting
#[cfg(feature = "console_error_panic_hook")]
extern crate console_error_panic_hook;

// Export plugin metadata for host discovery
#[wasm_bindgen(start)]
pub fn main() {
    log("uveddi-ai-linter plugin loaded");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_plugin_creation() {
        let plugin = UveddiAiLinter::new();
        assert_eq!(plugin.config.severity_threshold, 0.5);
    }

    #[test]
    fn test_line_number_finding() {
        let plugin = UveddiAiLinter::new();
        let code = "fn main() {\n    // TODO: implement\n    println!(\"Hello\");\n}";
        
        assert_eq!(plugin.find_line_number(code, "TODO"), 2);
        assert_eq!(plugin.find_line_number(code, "nonexistent"), 0);
    }

    #[test]
    fn test_complexity_calculation() {
        let plugin = UveddiAiLinter::new();
        let simple_code = "fn hello() { println!(\"hello\"); }";
        let complex_code = "fn test() { if x { if y { while z { for i in items { } } } } }";
        
        assert_eq!(plugin.calculate_complexity(simple_code), 1);
        assert!(plugin.calculate_complexity(complex_code) > 1);
    }
}