# Test Python file for AI-generated code detection

import sys
from typing import Dict, List, Optional

# This code was generated by ChatGPT/GPT-4 - typical AI comment
def process_data(data: List[int]) -> Dict[str, int]:
    """
    This function processes data and returns a dictionary.
    TODO: Add proper error handling and validation
    """
    result = {}
    
    # Placeholder implementation - needs review
    for item in data:
        key = f"item_{item}"
        result[key] = item * 2
    
    return result

# Generic variable names - AI signature
def helper_function(input_data: str) -> str:
    # TODO: Implement this properly
    temp = input_data.upper()
    return temp

class DataProcessor:
    """
    This class was automatically generated to handle data processing.
    """
    
    def __init__(self):
        self.data = []
        self.result = {}
        self.temp = ""
        
    def process(self):
        """Process the data according to business logic."""
        # This code processes the data step by step
        for index, item in enumerate(self.data):
            if item > 0:
                if item < 100:
                    if item % 2 == 0:
                        self.result[f"even_{index}"] = item
                    else:
                        self.result[f"odd_{index}"] = item
                else:
                    self.result[f"large_{index}"] = item
            else:
                self.result[f"negative_{index}"] = item

# Duplicate functions - AI pattern
def validate_input_1(input_str: str) -> bool:
    if not input_str:
        return False
    return input_str.isalnum()

def validate_input_2(input_str: str) -> bool:
    if not input_str:
        return False
    return input_str.isalnum()

# Magic numbers typical in AI-generated code
def calculate_score(base: int) -> int:
    return base * 42 + 1337 - 100

# Overly descriptive comments - AI signature
def complex_calculation(x: int, y: int) -> int:
    # First, we multiply x by 2
    temp1 = x * 2
    
    # Then, we add y to the result
    temp2 = temp1 + y
    
    # Finally, we subtract 10 and return the result
    final_result = temp2 - 10
    return final_result

# AI often generates extensive error handling examples
def safe_division(a: int, b: int) -> Optional[float]:
    try:
        if b == 0:
            print("Error: Division by zero")
            return None
        result = a / b
        return result
    except Exception as e:
        print(f"An error occurred: {e}")
        return None