// This is a test file for AI-generated code detection

use std::collections::HashMap;

// TODO: Implement this function properly
// This code was generated by AI assistant
pub fn process_data(data: Vec<i32>) -> HashMap<String, i32> {
    let mut result = HashMap::new();
    
    // Placeholder implementation - needs review
    for item in data {
        let key = format!("item_{}", item);
        result.insert(key, item * 2);
    }
    
    result
}

// Generic function name - typical AI pattern
pub fn helper_function(input: &str) -> String {
    // TODO: Add proper error handling
    input.to_uppercase()
}

// Potentially AI-generated - repetitive pattern
pub struct DataProcessor {
    pub data: Vec<i32>,
    pub result: HashMap<String, i32>,
    pub temp: String,
}

impl DataProcessor {
    pub fn new() -> Self {
        Self {
            data: Vec::new(),
            result: HashMap::new(),
            temp: String::new(),
        }
    }
    
    // Long method - potential AI generation indicator
    pub fn process(&mut self) {
        // This function processes the data
        for (index, item) in self.data.iter().enumerate() {
            if *item > 0 {
                if *item < 100 {
                    if *item % 2 == 0 {
                        self.result.insert(format!("even_{}", index), *item);
                    } else {
                        self.result.insert(format!("odd_{}", index), *item);
                    }
                } else {
                    self.result.insert(format!("large_{}", index), *item);
                }
            } else {
                self.result.insert(format!("negative_{}", index), *item);
            }
        }
    }
}

// Duplicate code pattern - AI often generates similar structures
pub fn validate_input1(input: &str) -> bool {
    if input.is_empty() {
        return false;
    }
    input.chars().all(|c| c.is_alphanumeric())
}

pub fn validate_input2(input: &str) -> bool {
    if input.is_empty() {
        return false;
    }
    input.chars().all(|c| c.is_alphanumeric())
}

// Magic numbers without explanation
pub fn calculate_score(base: i32) -> i32 {
    base * 42 + 1337 - 100
}