//! Component Model host implementation for WASM plugins
//!
//! This module implements the host-side functions that plugins can call,
//! using the Component Model interface generated by wasmtime::component::bindgen!().

use crate::plugins::security::{Permission, SecurityPolicy};
use crate::plugins::types::{PluginConfig, PluginId, ResourceLimits as InternalResourceLimits};
use std::collections::HashMap;
use std::path::Path;
use std::sync::Arc;
use tokio::sync::RwLock;

#[cfg(feature = "wasm-plugins")]
use wasmtime::component::ResourceTable;
#[cfg(feature = "wasm-plugins")]
use wasmtime_wasi::preview1::WasiP1Ctx;
#[cfg(feature = "wasm-plugins")]
use wasmtime_wasi::WasiView;

/// Host state for Component Model plugins
/// This combines WASI context with Uveddi-specific functionality
#[cfg(feature = "wasm-plugins")]
pub struct ComponentHostState {
    /// Plugin identifier
    pub plugin_id: PluginId,
    /// Plugin configuration
    pub config: PluginConfig,
    /// Security policy
    pub security_policy: SecurityPolicy,
    /// Resource limits
    pub resource_limits: InternalResourceLimits,
    /// WASI Preview 1 context
    pub wasi_ctx: WasiP1Ctx,
    /// Resource table for Component Model
    pub table: ResourceTable,
    /// Configuration key-value store
    pub config_store: HashMap<String, String>,
    /// Cached AST nodes (for query-ast operations)
    pub ast_cache: HashMap<String, crate::plugins::wasm::AstNode>,
}

#[cfg(feature = "wasm-plugins")]
impl std::fmt::Debug for ComponentHostState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ComponentHostState")
            .field("plugin_id", &self.plugin_id)
            .field("config", &self.config)
            .field("security_policy", &self.security_policy)
            .finish()
    }
}

#[cfg(feature = "wasm-plugins")]
impl WasiView for ComponentHostState {
    fn ctx(&mut self) -> wasmtime_wasi::WasiCtxView<'_> {
        self.wasi_ctx.ctx()
    }
}

/// Implementation of all host functions (imports) for the core-analysis world
/// The bindgen! macro generates a trait called `CoreAnalysisImports` that we must implement
#[cfg(feature = "wasm-plugins")]
impl crate::plugins::wasm::CoreAnalysisImports for ComponentHostState {
    /// Log a message from the plugin
    fn log(&mut self, level: crate::plugins::wasm::LogLevel, message: String) {
        use crate::plugins::wasm::LogLevel;
        match level {
            LogLevel::Trace => tracing::trace!("[Plugin {}] {}", self.plugin_id, message),
            LogLevel::Debug => tracing::debug!("[Plugin {}] {}", self.plugin_id, message),
            LogLevel::Info => tracing::info!("[Plugin {}] {}", self.plugin_id, message),
            LogLevel::Warn => tracing::warn!("[Plugin {}] {}", self.plugin_id, message),
            LogLevel::Error => tracing::error!("[Plugin {}] {}", self.plugin_id, message),
        }
    }

    /// Read a file from the filesystem
    fn read_file(&mut self, path: String) -> Result<String, String> {
        // Check permission
        if !self.security_policy.has_permission(&Permission::FileRead(path.clone().into())) {
            return Err(format!("Permission denied: cannot read file {}", path));
        }

        std::fs::read_to_string(&path)
            .map_err(|e| format!("Failed to read file {}: {}", path, e))
    }

    /// Write content to a file
    fn write_file(&mut self, path: String, content: String) -> Result<(), String> {
        // Check permission
        if !self.security_policy.has_permission(&Permission::FileWrite(path.clone().into())) {
            return Err(format!("Permission denied: cannot write file {}", path));
        }

        std::fs::write(&path, content)
            .map_err(|e| format!("Failed to write file {}: {}", path, e))
    }

    /// Check if a file exists
    fn file_exists(&mut self, path: String) -> bool {
        Path::new(&path).exists()
    }

    /// List files matching a pattern
    fn list_files(&mut self, pattern: String) -> Result<Vec<String>, String> {
        use glob::glob;
        
        let mut files = Vec::new();
        for entry in glob(&pattern).map_err(|e| format!("Invalid pattern: {}", e))? {
            match entry {
                Ok(path) => {
                    if let Some(s) = path.to_str() {
                        files.push(s.to_string());
                    }
                }
                Err(e) => {
                    tracing::warn!("Error reading path: {}", e);
                }
            }
        }
        Ok(files)
    }

    /// Get file metadata
    fn get_file_metadata(&mut self, path: String) -> Result<crate::plugins::wasm::FileMetadata, String> {
        use crate::plugins::wasm::FileMetadata;
        
        let metadata = std::fs::metadata(&path)
            .map_err(|e| format!("Failed to get metadata for {}: {}", path, e))?;

        let modified = metadata.modified()
            .map(|t| t.duration_since(std::time::UNIX_EPOCH).unwrap_or_default().as_secs())
            .unwrap_or(0);

        Ok(FileMetadata {
            size: metadata.len(),
            modified,
            is_directory: metadata.is_dir(),
            permissions: 0o644, // Default permissions
        })
    }

    /// Get a configuration value
    fn get_config(&mut self, key: String) -> Option<String> {
        self.config_store.get(&key).cloned()
    }

    /// Set a configuration value
    fn set_config(&mut self, key: String, value: String) -> Result<(), String> {
        if !self.security_policy.has_permission(&Permission::ConfigRead) {
            return Err("Permission denied: cannot modify configuration".to_string());
        }
        self.config_store.insert(key, value);
        Ok(())
    }

    /// Parse code into an AST
    fn parse_ast(&mut self, code: String, language: String) -> Result<crate::plugins::wasm::AstNode, String> {
        use crate::plugins::wasm::{AstNode, Position, Span};
        
        #[cfg(feature = "tree-sitter")]
        {
            // Get the appropriate tree-sitter language
            let ts_language = match language.as_str() {
                "rust" => tree_sitter_rust::LANGUAGE,
                "python" => tree_sitter_python::LANGUAGE,
                "javascript" => tree_sitter_javascript::LANGUAGE,
                "typescript" => tree_sitter_typescript::LANGUAGE_TYPESCRIPT,
                _ => return Err(format!("Unsupported language: {}", language)),
            };

            // Create parser and parse
            let mut parser = tree_sitter::Parser::new();
            parser.set_language(&ts_language.into())
                .map_err(|e| format!("Failed to set language: {}", e))?;

            let tree = parser.parse(&code, None)
                .ok_or_else(|| "Failed to parse code".to_string())?;

            // Convert tree-sitter node to WIT AstNode
            let root = tree.root_node();
            let ast_node = self.convert_ts_node_to_wit(&root, &code, &language);
            
            // Cache the AST for query-ast operations
            let cache_key = format!("{}:{}", self.plugin_id, code.len());
            self.ast_cache.insert(cache_key, ast_node.clone());
            
            Ok(ast_node)
        }

        #[cfg(not(feature = "tree-sitter"))]
        {
            // Return a minimal root node when tree-sitter is not available
            Ok(AstNode {
                node_type: "root".to_string(),
                content: code.clone(),
                span: Span {
                    start: Position { line: 0, column: 0, byte_offset: 0 },
                    end: Position { 
                        line: code.lines().count() as u32, 
                        column: 0, 
                        byte_offset: code.len() as u32 
                    },
                },
                language: language.clone(),
                attributes: vec![],
            })
        }
    }

    /// Query an AST using tree-sitter query syntax
    fn query_ast(&mut self, node: crate::plugins::wasm::AstNode, query: String) -> Result<Vec<crate::plugins::wasm::AstNode>, String> {
        // For now, return an empty list - full query implementation would require 
        // maintaining actual tree-sitter trees and executing queries against them
        tracing::debug!("query_ast called with query: {}", query);
        
        // Return empty results - tree-sitter queries require the actual tree structure
        // which we don't have from just the AstNode representation
        Ok(vec![])
    }

    /// Calculate a hash of content
    fn calculate_hash(&mut self, algorithm: String, content: String) -> Result<String, String> {
        use sha2::{Sha256, Sha512, Digest};
        
        match algorithm.to_lowercase().as_str() {
            "sha256" => {
                let mut hasher = Sha256::new();
                hasher.update(content.as_bytes());
                Ok(format!("{:x}", hasher.finalize()))
            }
            "sha512" => {
                let mut hasher = Sha512::new();
                hasher.update(content.as_bytes());
                Ok(format!("{:x}", hasher.finalize()))
            }
            _ => Err(format!("Unsupported hash algorithm: {}", algorithm)),
        }
    }

    /// Verify a signature
    fn verify_signature(&mut self, _content: String, _signature: String, _public_key: String) -> Result<bool, String> {
        // Signature verification would require a crypto library
        Err("Signature verification not yet implemented".to_string())
    }

    /// Make an HTTP GET request
    fn http_get(&mut self, url: String, headers: Vec<(String, String)>) -> Result<crate::plugins::wasm::HttpResponse, String> {
        use crate::plugins::wasm::HttpResponse;
        
        // Check network permission
        if !self.security_policy.permissions.iter().any(|p| matches!(p, Permission::NetworkConnect(_))) {
            return Err("Permission denied: network access not allowed".to_string());
        }

        // For now, return an error - async HTTP would need different handling
        Err("HTTP requests require async context - not yet implemented in sync host functions".to_string())
    }

    /// Make an HTTP POST request
    fn http_post(&mut self, url: String, body: String, headers: Vec<(String, String)>) -> Result<crate::plugins::wasm::HttpResponse, String> {
        use crate::plugins::wasm::HttpResponse;
        
        // Check network permission
        if !self.security_policy.permissions.iter().any(|p| matches!(p, Permission::NetworkConnect(_))) {
            return Err("Permission denied: network access not allowed".to_string());
        }

        Err("HTTP requests require async context - not yet implemented in sync host functions".to_string())
    }

    /// Get a value from the database cache
    fn db_get(&mut self, key: String) -> Option<String> {
        // For now, use the config store as a simple cache
        self.config_store.get(&format!("db:{}", key)).cloned()
    }

    /// Set a value in the database cache
    fn db_set(&mut self, key: String, value: String, ttl_seconds: Option<u32>) -> Result<(), String> {
        // For now, use the config store as a simple cache (ttl ignored)
        self.config_store.insert(format!("db:{}", key), value);
        Ok(())
    }

    /// Delete a value from the database cache
    fn db_delete(&mut self, key: String) -> Result<bool, String> {
        let existed = self.config_store.remove(&format!("db:{}", key)).is_some();
        Ok(existed)
    }

    /// Get process information
    fn get_process_info(&mut self) -> Result<crate::plugins::wasm::ProcessInfo, String> {
        use crate::plugins::wasm::ProcessInfo;
        use sysinfo::System;
        
        let mut sys = System::new_all();
        sys.refresh_all();
        
        let pid = std::process::id();
        
        // Get current process info
        if let Some(process) = sys.process(sysinfo::Pid::from_u32(pid)) {
            Ok(ProcessInfo {
                pid,
                memory_usage_mb: (process.memory() / 1024 / 1024) as u32,
                cpu_usage_percent: process.cpu_usage(),
                uptime_seconds: process.run_time() as u32,
            })
        } else {
            Ok(ProcessInfo {
                pid,
                memory_usage_mb: 0,
                cpu_usage_percent: 0.0,
                uptime_seconds: 0,
            })
        }
    }
}

#[cfg(feature = "wasm-plugins")]
impl ComponentHostState {
    /// Create a new component host state
    pub fn new(
        plugin_id: PluginId,
        config: PluginConfig,
        security_policy: SecurityPolicy,
        wasi_ctx: WasiP1Ctx,
    ) -> Self {
        Self {
            plugin_id,
            config: config.clone(),
            security_policy: security_policy.clone(),
            resource_limits: security_policy.resource_limits.clone(),
            wasi_ctx,
            table: ResourceTable::new(),
            config_store: config.custom_settings.clone(),
            ast_cache: HashMap::new(),
        }
    }

    /// Convert a tree-sitter node to a WIT AstNode
    #[cfg(feature = "tree-sitter")]
    fn convert_ts_node_to_wit(
        &self,
        node: &tree_sitter::Node,
        source: &str,
        language: &str,
    ) -> crate::plugins::wasm::AstNode {
        use crate::plugins::wasm::{AstNode, Position, Span};

        let start = node.start_position();
        let end = node.end_position();

        AstNode {
            node_type: node.kind().to_string(),
            content: node.utf8_text(source.as_bytes()).unwrap_or("").to_string(),
            span: Span {
                start: Position {
                    line: start.row as u32,
                    column: start.column as u32,
                    byte_offset: node.start_byte() as u32,
                },
                end: Position {
                    line: end.row as u32,
                    column: end.column as u32,
                    byte_offset: node.end_byte() as u32,
                },
            },
            language: language.to_string(),
            attributes: vec![
                ("named".to_string(), node.is_named().to_string()),
                ("child_count".to_string(), node.child_count().to_string()),
            ],
        }
    }
}
