apiVersion: v1
kind: Namespace
metadata:
  name: uveddi
  labels:
    name: uveddi
    app.kubernetes.io/name: uveddi
    app.kubernetes.io/part-of: uveddi-platform
  annotations:
    # Security policies
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted